jobs:
  linux:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: Spotless Check
      run: ./gradlew spotlessCheck
    - continue-on-error: true
      name: Gradle Build
      run: ./gradlew assembleRelease
    - continue-on-error: true
      name: Upload ARM64
      uses: actions/upload-artifact@v4
      with:
        name: arm64-v8a-${{ github.sha }}
        path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
    - continue-on-error: true
      name: Upload x86_64
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-${{ github.sha }}
        path: app/build/outputs/apk/release/app-x86_64-release.apk
    - continue-on-error: true
      name: Upload ARM32
      uses: actions/upload-artifact@v4
      with:
        name: armeabi-v7a-${{ github.sha }}
        path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    - continue-on-error: true
      name: Upload x86
      uses: actions/upload-artifact@v4
      with:
        name: x86-${{ github.sha }}
        path: app/build/outputs/apk/release/app-x86-release.apk
    - continue-on-error: true
      name: Upload mapping
      uses: actions/upload-artifact@v4
      with:
        name: mapping-${{ github.sha }}
        path: app/build/outputs/mapping/release/mapping.txt
        retention-days: 5
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
